---
galaxy_info:
  author: ericsysmin
  role_name: chrony
  company: ericsymsin
  description: This role enables users to install and configure chrony on their hosts.
  license: MIT
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 7
    - name: Debian
      versions:
        - jessie
        - stretch
  galaxy_tags:
    - system
    - chrony
    - ntp
    - time
dependencies: []
