---
dist: bionic
os: linux
language: python
services:
  - docker

before_install:
  - sudo apt-get -qq update

env:
  global:
    - COLLECTION_NAMESPACE: ericsysmin
    - COLLECTION_NAME: system
  jobs:
    - ROLE=chrony MOLECULE_DISTRO=centos-7 MOLECULE_COMMAND=/usr/sbin/init
    - ROLE=chrony MOLECULE_DISTRO=centos-8 MOLECULE_COMMAND=/usr/sbin/init
    - ROLE=chrony MOLECULE_DISTRO=fedora-32 MOLECULE_COMMAND=/usr/sbin/init
    - ROLE=chrony MOLECULE_DISTRO=fedora-31 MOLECULE_COMMAND=/usr/lib/systemd/systemd
    - ROLE=chrony MOLECULE_DISTRO=fedora-30 MOLECULE_COMMAND=/usr/lib/systemd/systemd
    - ROLE=chrony MOLECULE_DISTRO=ubuntu-16.04 MOLECULE_COMMAND=/sbin/init
    - ROLE=chrony MOLECULE_DISTRO=ubuntu-18.04 MOLECULE_COMMAND=/lib/systemd/systemd
    - ROLE=chrony MOLECULE_DISTRO=ubuntu-20.04 MOLECULE_COMMAND=/lib/systemd/systemd
    - ROLE=chrony MOLECULE_DISTRO=debian-9 MOLECULE_COMMAND=/lib/systemd/systemd
    - ROLE=chrony MOLECULE_DISTRO=debian-10 MOLECULE_COMMAND=/lib/systemd/systemd

    - ROLE=epel MOLECULE_DISTRO=centos-7 MOLECULE_COMMAND=/usr/sbin/init
    - ROLE=epel MOLECULE_DISTRO=centos-8 MOLECULE_COMMAND=/usr/sbin/init

    - ROLE=logrotate MOLECULE_DISTRO=centos-7 MOLECULE_COMMAND=/usr/sbin/init
    - ROLE=logrotate MOLECULE_DISTRO=centos-8 MOLECULE_COMMAND=/usr/sbin/init
    - ROLE=logrotate MOLECULE_DISTRO=ubuntu-16.04 MOLECULE_COMMAND=/sbin/init
    - ROLE=logrotate MOLECULE_DISTRO=ubuntu-18.04 MOLECULE_COMMAND=/lib/systemd/systemd
    - ROLE=logrotate MOLECULE_DISTRO=ubuntu-20.04 MOLECULE_COMMAND=/lib/systemd/systemd
    - ROLE=logrotate MOLECULE_DISTRO=debian-9 MOLECULE_COMMAND=/lib/systemd/systemd
    - ROLE=logrotate MOLECULE_DISTRO=debian-10 MOLECULE_COMMAND=/lib/systemd/systemd

    - ROLE=ntp MOLECULE_DISTRO=centos-7 MOLECULE_COMMAND=/usr/sbin/init
    - ROLE=ntp MOLECULE_DISTRO=ubuntu-16.04 MOLECULE_COMMAND=/sbin/init
    - ROLE=ntp MOLECULE_DISTRO=ubuntu-18.04 MOLECULE_COMMAND=/lib/systemd/systemd
    - ROLE=ntp MOLECULE_DISTRO=debian-9 MOLECULE_COMMAND=/lib/systemd/systemd

    - ROLE=remi_repo MOLECULE_DISTRO=centos-7 MOLECULE_COMMAND=/usr/sbin/init

    - ROLE=selinux MOLECULE_DISTRO=centos-7 MOLECULE_COMMAND=/usr/sbin/init

jobs:
  fast_finish: true
install:
  - pip install molecule yamllint ansible-lint docker

before_script:
  - cd ../
  - mkdir -p ansible_collections/$COLLECTION_NAMESPACE
  - mv ansible-collection-$COLLECTION_NAME ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME
  - cd ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME

script:
  - molecule test --scenario-name $ROLE
