---
galaxy_info:
  author: ericsymsin
  role_name: epel
  description: Role to configure EPEL on RHEL/CentOS based systems
  license: MIT
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 6
        - 7
        - 8
  galaxy_tags:
    - epel
    - rhel
    - centos
dependencies: []
